#!/usr/bin/env python3
"""
Zero-to-Hero One-Click Installer for Mainland China Android TVs.
Fully automated deployment of YouTube (SmartTube) + Background Native Proxy Daemon (Mihomo).
Works on Skyworth, Coocaa, Xiaomi, Sony, TCL, Hisense, etc.
"""

import argparse
import subprocess
import os
import sys
import time
import urllib.request
import json

DEFAULT_TV_IP = "192.168.0.116"

TV_CONFIG_TEMPLATE = """# Auto-generated by setup_tv.py for Android TV
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
ipv6: false
tcp-concurrent: true
keep-alive-idle: 600
find-process-mode: "off"
external-controller: 0.0.0.0:9090
secret: ''

dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 119.29.29.29
    - https://dns.google/dns-query

"""

def get_adb_path(custom_path=None):
    if custom_path and os.path.exists(custom_path):
        return custom_path
    if subprocess.run(["where", "adb"], capture_output=True).stdout:
        return "adb"
    candidates = [
        r"C:\Users\Administrator\Desktop\adb_tools\platform-tools\adb.exe",
        r"D:\adb\adb.exe",
        r"C:\adb\adb.exe"
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    return "adb"

def run_adb(adb, target, cmd_args):
    return subprocess.run([adb, "-s", target] + cmd_args, capture_output=True, text=True, encoding="utf-8", errors="ignore")

def setup_tv(tv_ip, sub_url=None, local_config=None, adb_path=None):
    adb = get_adb_path(adb_path)
    target = f"{tv_ip}:5555"

    print("=" * 65)
    print(" 🚀 大陆普通安卓电视一键接入 YouTube (SmartTube) 部署工具")
    print(f" 🎯 目标电视 IP: {tv_ip}")
    print("=" * 65)

    # 1. Connect ADB
    print("\n[1/6] 正在通过 ADB 连接电视...")
    subprocess.run([adb, "connect", target], capture_output=True)
    r = subprocess.run([adb, "devices"], capture_output=True, text=True)
    if target not in r.stdout:
        print(f"[!] 无法连接到电视 {target}。请确认：")
        print("    1. 电视与电脑处于同一 Wi-Fi 局域网")
        print("    2. 电视【设置】->【关于】已开启【ADB 调试 / 通用调试】")
        return False
    print("[+] ADB 远程连接成功！")

    # 2. Push and install SmartTube APK if not installed
    print("\n[2/6] 检查并安装 SmartTube (YouTube 电视版)...")
    installed = "org.smarttube.stable" in run_adb(adb, target, ["shell", "pm", "list", "packages", "org.smarttube.stable"]).stdout
    if installed:
        print("[+] 电视已安装 SmartTube，跳过 APK 安装。")
    else:
        apk_candidates = [
            os.path.join(os.path.dirname(__file__), "..", "release_assets", "SmartTube_Stable.apk"),
            r"C:\Users\Administrator\Desktop\创维电视YouTube安装包\1_SmartTube_YouTube电视版_稳定版.apk"
        ]
        apk_path = next((p for p in apk_candidates if os.path.exists(p)), None)
        if apk_path:
            print(f"[*] 正在推送并安装 SmartTube: {os.path.basename(apk_path)} ...")
            run_adb(adb, target, ["install", "-r", apk_path])
            print("[+] SmartTube 安装成功！")
        else:
            print("[-] 未在本地找到 SmartTube APK，请手动安装或从 GitHub Releases 下载。")

    # 3. Push native Linux Mihomo daemon binary
    print("\n[3/6] 部署底层常驻 Linux 代理守护进程 (Mihomo)...")
    bin_candidates = [
        os.path.join(os.path.dirname(__file__), "..", "release_assets", "mihomo"),
        r"C:\Users\Administrator\Desktop\创维电视YouTube安装包\mihomo"
    ]
    bin_path = next((p for p in bin_candidates if os.path.exists(p)), None)
    if bin_path:
        print(f"[*] 正在将原生二进制推送到电视 `/data/local/tmp/mihomo` ...")
        run_adb(adb, target, ["push", bin_path, "/data/local/tmp/mihomo"])
        run_adb(adb, target, ["shell", "chmod", "755", "/data/local/tmp/mihomo"])
        print("[+] 守护进程二进制部署完成！")
    else:
        print("[+] 验证电视已有守护程序...")
        run_adb(adb, target, ["shell", "chmod", "755", "/data/local/tmp/mihomo"])

    # 4. Fetch subscription and optimize for TV
    print("\n[4/6] 配置机场订阅与节点...")
    raw_config = ""
    if sub_url:
        print(f"[*] 正在下载订阅配置: {sub_url} ...")
        headers = {"User-Agent": "ClashMeta; ClashVerge; ClashforWindows"}
        req = urllib.request.Request(sub_url, headers=headers)
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw_config = resp.read().decode("utf-8", errors="ignore")
    elif local_config and os.path.exists(local_config):
        with open(local_config, "r", encoding="utf-8", errors="ignore") as f:
            raw_config = f.read()

    if raw_config and "proxies:" in raw_config:
        import re
        m = re.search(r'\n(?=(proxies:|proxy-providers:))', raw_config)
        body = raw_config[m.start():] if m else raw_config
        opt_config = TV_CONFIG_TEMPLATE.strip() + "\n\n" + body.lstrip()
        
        tmp_file = os.path.join(os.path.dirname(__file__), "tmp_tv_config.yaml")
        with open(tmp_file, "w", encoding="utf-8") as f:
            f.write(opt_config)
        
        run_adb(adb, target, ["shell", "mkdir", "-p", "/sdcard/mihomo"])
        run_adb(adb, target, ["push", tmp_file, "/sdcard/mihomo/config.yaml"])
        if os.path.exists(tmp_file):
            os.remove(tmp_file)
        print("[+] 订阅节点已注入并推送到电视 `/sdcard/mihomo/config.yaml`！")
    else:
        print("[*] 保持电视当前现有订阅配置。")

    # 5. Start / Restart Mihomo daemon
    print("\n[5/6] 启动底层后台代理服务...")
    run_adb(adb, target, ["shell", "killall mihomo 2>/dev/null || true"])
    time.sleep(1)
    run_adb(adb, target, ["shell", "nohup /data/local/tmp/mihomo -d /sdcard/mihomo > /dev/null 2>&1 &"])
    time.sleep(2)
    print("[+] 底层守护进程已常驻运行 (端口: 127.0.0.1:7890)！")

    # 6. Bind SmartTube and Android Global Proxy
    print("\n[6/6] 绑定 SmartTube 及系统代理至 127.0.0.1:7890...")
    run_adb(adb, target, ["shell", "settings", "put", "global", "http_proxy", "127.0.0.1:7890"])
    run_adb(adb, target, ["shell", "settings", "put", "global", "global_http_proxy_host", "127.0.0.1"])
    run_adb(adb, target, ["shell", "settings", "put", "global", "global_http_proxy_port", "7890"])

    # Launch SmartTube
    run_adb(adb, target, ["shell", "am", "force-stop", "org.smarttube.stable"])
    time.sleep(1)
    run_adb(adb, target, ["shell", "monkey", "-p", "org.smarttube.stable", "-c", "android.intent.category.LAUNCHER", "1"])
    print("[+] SmartTube 已在电视上启动！")

    print("\n" + "=" * 65)
    print(" 🎉 恭喜！电视端 YouTube 部署全部就绪！")
    print(" 💡 电视已独立运行代理，关掉电脑也不受任何影响，直接拿遥控器看即可。")
    print("=" * 65)
    return True

def main():
    parser = argparse.ArgumentParser(description="One-Click Android TV YouTube Setup Tool")
    parser.add_argument("--tv-ip", default=DEFAULT_TV_IP, help="Android TV IP address")
    parser.add_argument("--sub-url", help="Airport Clash subscription link")
    parser.add_argument("--config", help="Local Clash YAML config file path")
    parser.add_argument("--adb-path", help="Path to custom adb executable")
    args = parser.parse_args()

    setup_tv(args.tv_ip, sub_url=args.sub_url, local_config=args.config, adb_path=args.adb_path)

if __name__ == "__main__":
    main()
